# Generated by Django 3.2.25 on 2025-10-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHTmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
