# Generated by Django 3.2.25 on 2024-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0205_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avt_url',
            field=models.SlugField(default=''),
        ),
    ]
