# Generated by Django 3.2.25 on 2024-07-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0206_profile_avt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avt_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
