# Generated by Django 3.2.25 on 2024-07-27 14:30

from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0210_alter_profile_avt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avt_url',
            field=models.FileField(blank=True, null=True, upload_to=judge.models.profile.user_directory_path),
        ),
    ]
