unit:
  runs-on: ubuntu-latest
  services:
    mysql:
      image: mysql:8.0
      env:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dmoj
      ports:
        - 3306:3306
      options: >-
        --health-cmd="mysqladmin ping -h localhost -uroot -proot"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3
  env:
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('requirements.txt') }}
    - name: Install unit test dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
        pip install coverage
        cp .ci.settings.py dmoj/local_settings.py
    - name: Wait for MySQL
      run: |
        until mysql -h 127.0.0.1 -uroot -proot -e "SELECT 1"; do
          echo "Waiting for MySQL..."
          sleep 5
        done
    - name: Run migrations
      run: |
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Run unit tests
      run: coverage run --source=. manage.py test judge
    - name: Generate coverage report
      run: coverage xml
